### ISSUE TITLE
Result: Err(Panic) on attempt to run any test: Failed to pin to core!

### ISSUE THREAD

**Issue by rob-p** [pairwise-alignment/pa-bench#1]
First, I think this seems like an *amazing* resource; thanks for spearheading this effort!

I'm trying to run a basic test using the interface described in the readme (as are some students in a class I'm teaching doing a project that compares different aligners), and we're both running into the same problem.  I can run the yaml experiment to e.g. download the data, but trying to run any experiment that invokes the aligners results in an `Err(Panic)` for every test.  For example, I tried:

```
cargo run --release -- --rerun-all evals/experiments/unit.yaml
```

and the output is:

```
 Processed: 732 / 800. Success   0, Unsupported   0, Failed  20, Skipped 712
 Failed job:
{"time_limit":600,"mem_limit":68719476736,"dataset":{"Generated":{"prefix":"evals/data/generated","seed":31415,"error_model":"Independent","error_rate":1.0,"length":100,"total_size":100000,"pattern_length":null}},"costs":{"sub":1,"open":0,"extend":1},"traceback":true,"algo":{"Wfa":{"memory_model":"MemoryUltraLow","heuristic":"None"}}}
 Result: Err(Panic)
 ResourceUsage { walltime: 0.004629624, usertime: 0.002235, systemtime: 0.002126, maxrss: 2527232 }

 Processed: 733 / 800. Success   0, Unsupported   0, Failed  21, Skipped 712
 Failed job:
{"time_limit":600,"mem_limit":68719476736,"dataset":{"Generated":{"prefix":"evals/data/generated","seed":31415,"error_model":"Independent","error_rate":1.0,"length":100,"total_size":100000,"pattern_length":null}},"costs":{"sub":1,"open":0,"extend":1},"traceback":true,"algo":{"TripleAccel":null}}
 Result: Err(Panic)
 ResourceUsage { walltime: 0.004609295, usertime: 0.002177, systemtime: 0.002212, maxrss: 2519040 }

 Processed: 734 / 800. Success   0, Unsupported   0, Failed  22, Skipped 712
 Failed job:
{"time_limit":600,"mem_limit":68719476736,"dataset":{"Generated":{"prefix":"evals/data/generated","seed":31415,"error_model":"Independent","error_rate":1.0,"length":100,"total_size":100000,"pattern_length":null}},"costs":{"sub":1,"open":0,"extend":1},"traceback":true,"algo":{"Ksw2":{"method":"GlobalSuzukiSse","band_doubling":true}}}
 Result: Err(Panic)
 ResourceUsage { walltime: 0.004575984, usertime: 0.002254, systemtime: 0.001902, maxrss: 2498560 }

 Processed: 799 / 800. Success   0, Unsupported   0, Failed  23, Skipped 776
 Failed job:
{"time_limit":600,"mem_limit":68719476736,"dataset":{"Generated":{"prefix":"evals/data/generated","seed":31415,"error_model":"Independent","error_rate":1.0,"length":200,"total_size":100000,"pattern_length":null}},"costs":{"sub":1,"open":0,"extend":1},"traceback":true,"algo":{"Ksw2":{"method":"GlobalSuzukiSse","band_doubling":true}}}
 Result: Err(Panic)
 ResourceUsage { walltime: 0.003512353, usertime: 0.001935, systemtime: 0.001576, maxrss: 2486272 }

 Processed: 800 / 800. Success   0, Unsupported   0, Failed  24, Skipped 776
Output: 800 jobs to evals/results/unit.json
Output: 800 jobs to evals/results/unit.cache.json
```

preceded by many other failed jobs.  Any idea what might be going on here?  I'm on OSX 10.15.7, on and x86-based mac running rust 1.71 nightly.

Thanks!
Rob

**Comment by RagnarGrootKoerkamp** [comment]
I'm on it :)

I think in the process of adding new stuff some things broke along the way :sweat_smile: 

edit: unlikely actually; this particular experiment doesn't run A*PA related code, and the other crates are very stable.

**Comment by RagnarGrootKoerkamp** [comment]
Oh, did you build the `runner` first? `cargo build --release [--bin runner]`. Here everything seems to work.

I'll add to the docs. (My plan is to actually merge the two binaries into just one that calls itself, to save this overhead of compiling many things twice.)

**Comment by RagnarGrootKoerkamp** [comment]
You can also do `cargo run --release -- --rerun-all <path> --verbose --stderr` to show the logs of the failing jobs, that would help debugging for me.

**Comment by IsabelF98** [comment]
Hello. I am one of @rob-p's student and the one trying to run the package. I am new to Rust and not quite sure what you mean by build the `runner`. Is there something I should be putting into `[--bin runner]`?

**Comment by RagnarGrootKoerkamp** [comment]
So this repo contains a few crates ('packages'):
- `pa-bench-types`: a library with common types
- `runner`: a binary that executes the external tools
- `orchestrator`: a binary that takes a `yaml` configuration file and calls the `runner` for each input/tool combination.
This 2-stage setup is useful/needed to better handle panics and so that we can memory usage via the OS.

Either way, this means that to run the `orchestrator`, you first need to build the `runner`. `cargo build --release --bin runner` does that, or you can do `cargo build --release` which builds both binaries at once.

**Comment by IsabelF98** [comment]
I ran
`cargo build --release --bin runner`
and got
`Finished release [optimized] target(s) in 0.34s`
so it seems to me that everything has been built. But I still get the same error as before.

**Comment by RagnarGrootKoerkamp** [comment]
Can you paste some output of
`cargo run --release -- --rerun-all evals/experiments/unit.yaml --verbose --stderr`
That should help me debugging this -- for me locally everything works

**Comment by IsabelF98** [comment]
I ran
`cargo run --release -- --rerun-all evals/experiments/tests/largestgap.yaml --verbo
se --stderr`
since it only had 1 job and got,
<img width="1103" alt="Screenshot 2023-05-04 at 6 09 35 PM" src="https://user-images.githubusercontent.com/64856859/236340424-7ec5419f-ef10-457d-8b47-4e0fc18348ce.png">

**Comment by RagnarGrootKoerkamp** [comment]
Ah ok, the `Failed to pin to core!` here is the problem:
To improve the benchmarks, each job is 'pinned' to a single core, so that it doesn't jump between cores during the executing. This should make timings slightly more reliable and make it easier to run things in parallel.

But probably the API I'm using doesn't work on OSX. I've just pushed a new version with a `--no-pin` flag that skips this step:
`cargo run --release -- --rerun-all --no-pin <path>`

**Comment by IsabelF98** [comment]
That did it! Thank you so much.

**Comment by RagnarGrootKoerkamp** [comment]
You're welcome :) I'll add a note to the readme for this.

Let me know if you have suggestions to improve useability and/or documentation!
